name: Update Data and Deploy

on:
  push:
    branches:
      - master
  schedule:
   - cron: "15 0,8,16 * * *"

jobs:
  syncData:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          path: master
    - name: Show files
      working-directory: ${{ github.workspace }}
      run:  ls -la
    - name: Checkout data repo
      uses: actions/checkout@v2
      with:
          repository: maxMaxineChen/COVID-19-worldwide-json-data-script
          path: sourceData
    - name: Copy the data file
      working-directory: ${{ github.workspace }}
      run:  |
           mkdir -p master/data
           cp sourceData/data/data.json master/data/data.json
    - name: Install
      run:  |
           cd master 
           npm install
           npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           personal_token: ${{ secrets.COVID }}
           publish_dir: ./master/public
